services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - C:/Projetos/rabbit:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "status"]
      interval: 30s
      timeout: 10s
      retries: 3

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: certificado
      MYSQL_DATABASE: ecommerce
    ports:
      - "3306:3306"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  redisinsight:
    image: redis/redisinsight:latest
    ports:
      - "5540:5540"
    environment:
      - REDISINSIGHT_AUTH_USERNAME=admin
      - REDISINSIGHT_AUTH_PASSWORD=admin123

  produtor:
    build:
      context: ./produtor
      dockerfile: Dockerfile
    environment:
      - RABBITMQ_HOST=rabbitmq
    depends_on:
      - rabbitmq
    ports:
      - "3000:3000"

  consumidor:
    build:
      context: ./consumidor
      dockerfile: Dockerfile
    environment:
      - RABBITMQ_HOST=rabbitmq
    depends_on:
      - rabbitmq
      
    # worker:
    #   image: node:latest
    #   ports:
    #     - 80:80
    #   volumes:
    #     - C:/Projetos/diploma:/diploma   

volumes:
  rabbitmq_data: