version: '3.8'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: prog_diplomas
    ports:
      - "3306:3306"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  redisinsight:
    image: redis/redisinsight:latest
    ports:
      - "5540:5540"
    environment:
      - REDISINSIGHT_AUTH_USERNAME=admin
      - REDISINSIGHT_AUTH_PASSWORD=admin123

volumes:
  db_data:
  redis_data:
  diploma_data:
